### ISSUE TITLE
Composer update failed

### ISSUE THREAD

**Issue by s7sundar** [weboAp/lar-carabiner#3]
When I am adding this package in laravel composer.json under `require` block I got this following error.  After updating this package. Help me how to resolve this.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for weboap/carabiner dev-master -> satisfiable by weboap/carabiner[dev-master].
    - weboap/carabiner dev-master requires natxet/cssmin dev-master -> no matching package found.

**Comment by s7sundar** [comment]
Hi,

All modules are exist in dev stage hence the above error is occured. However we can solve this issue by adding these following lines in composer.json file.

<pre>
"minimum-stability": "dev",
"prefer-stable" : true 
</pre>

Do we have any idea to make available this package under **STABLE**

<pre>
"minimum-stability": "stable",
</pre>

**Comment by weboAp** [comment]
fixed the requirement issue, test and let me know,
thanks for the heads up! will be working on a stable version for lar 5.
